### ISSUE TITLE
Usage in Harvester

### ISSUE THREAD

**Issue by dgiebert** [openSUSE/fuel-ignition#13]
When using the created image in harvester, it complains:

> Upload failed: the uploaded file size 20482460 should be a multiple of 512 bytes since Longhorn uses directIO by default

**Comment by dgiebert** [comment]
Forgot to convert to ISO first. maybe that could also be done in the browser?

**Comment by laenion** [comment]
Fixed in 1f576c57e8eef3175e0799524d347a77642d2e88 and deployed.
