### ISSUE TITLE
importing a fuel-ignition.json breaks Install Additional Packages 

### ISSUE THREAD

**Issue by 23flash** [openSUSE/fuel-ignition#40]
Whilst using the tool I noticed that if I try to press the  **Add** Button at "Install Additional Packages", after loading a fuel-ignition.json ,  Im taken back to https://opensuse.github.io/fuel-ignition/edit.  Which does not seem indented. 

To Replicate: 
- make a simple ignition config using Fuel ignition  (add a username with random password)
- Export to fuel-ignition.json
- Reload the page 
- reimport fuel-ignition.json 
- try to press the **Add**  button  at   "Install Additional Packages"

Im using the latest flatpak version of firefox no plugins installed.

**Comment by schubi2** [comment]
Hm, I have not found exactly that behaviour but the package name has been empty after the JSON file has been loaded. That has produced an unrelated behaviour which I have fixed ti will be available with the next release. Thank you !
