### ISSUE TITLE
Error: "~/.local/share/containers/storage/btrfs" is not on a btrfs filesystem

### ISSUE THREAD

**Issue by malcolmlewis** [openSUSE/fuel-ignition#5]
Hi
On openSUSE Tumbleweed a fresh install of podman uses fuse-overlayfs as follows;

```
zypper in podman

The following 3 recommended packages were automatically selected:
cni-plugins criu podman-cni-config

The following 13 NEW packages are going to be installed:
catatonit cni cni-plugins conmon criu fuse-overlayfs libcontainers-common libnet9 podman podman-cni-config python38-protobuf runc slirp4netns
```

When running make for the first time I get the following error;

```
make

podman build --build-arg CONTAINER_USERID=1000 -t fuelignition .
Error: "~/.local/share/containers/storage/btrfs" is not on a btrfs filesystem: prerequisites for driver not satisfied (wrong filesystem?)
make: *** [Makefile:4: all] Error 125
```

It seems one needs to create this storage configuration and was fixed with the following;

```
rm -rf ~/.local/share/containers/storage

mkdir -p ~/.config/containers/storage

echo -e "[storage]\ndriver = \"overlay\"" > ~/.config/containers/storage.conf
```

Now it's all working;

```
make

podman run --network=host fuelignition:latest &

xdg-open http://localhost:3000/fuel-ignition/ > /dev/null 2>&1
```

Perhaps the README can be updated with this information?

Note, I also used xdg-open as this will open the default browser for the user.

**Comment by grisu48** [comment]
To me this looks like https://bugzilla.opensuse.org/show_bug.cgi?id=1197093

Do you have your `/home` directory on a different filesystem? If so, changing the default driver from `"btrfs"` to `"overlay"` in your `/etc/containers/storage.conf` file might solve the issue.

    # /etc/containers/storage.conf
    driver = "overlay"           # Workaround for bsc#1197093

**Comment by faeller** [comment]
since this seems to not be related to FI, I'll close the issue :+1:
